# Generated by Django 5.0.6 on 2024-05-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_air_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air',
            old_name='price',
            new_name='aholi',
        ),
    ]
