# Generated by Django 5.0.6 on 2024-05-19 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0003_rename_price_air_aholi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('air', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.air')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='air.category')),
            ],
        ),
    ]
