# Generated by Django 5.0.6 on 2024-05-19 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0004_reys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reys',
            name='category',
        ),
        migrations.AlterField(
            model_name='reys',
            name='air',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airs', to='air.air'),
        ),
    ]
