# Generated by Django 5.0.6 on 2024-05-19 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0005_remove_reys_category_alter_reys_air'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reys',
            name='air',
        ),
        migrations.AddField(
            model_name='reys',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='air.category'),
        ),
    ]
