# Generated by Django 5.0.6 on 2024-05-19 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0007_alter_reys_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reys',
            name='category',
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aholi', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='reys_images')),
                ('reys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reys', to='air.reys')),
            ],
        ),
    ]
